### ISSUE TITLE
Library versions

### ISSUE THREAD

**Issue by Maxxx991** [amitt1236/Gaze_estimation#5]
Hello! Сan you tell me  versions of the libraries and the interpreter version?

**Comment by leofidus** [comment]
It seems to be quite tollerant to different library versions. I got it to run with

```bash
conda create --name gaze-estimation opencv numpy python=3.10
conda activate gaze-estimation
pip install mediapipe
python main.py
```

The python 3.10 is just because mediapipe isn't available yet for 3.12, I believe 3.11 would also work.

Only adjustment I had to make is change the selected camera in main.py, and fix the `cv2.cv2` in line 70 of gaze.py to just `cv2`
